/*
 * (C) 2015 TekMonks. All rights reserved.
 * License: MIT - see enclosed license.txt file.
 */

const FRONTEND = "https://{{{hostname}}}";
const BACKEND = "https://{{{hostname}}}:8443";
const APP_NAME = "tekmonks";
const APP_PATH = `${FRONTEND}/apps/tekmonks`;
const API_PATH = `${BACKEND}/apps/tekmonks`;
const CONF_PATH = `${FRONTEND}/apps/${APP_NAME}/conf`;
const INDEX_HTML = APP_PATH+"/index.html";
const LOGIN_HTML = APP_PATH+"/login.html";
const LOGINRESULT_HTML = APP_PATH+"/loginresult.html";

export const APP_CONSTANTS = {
    FRONTEND, BACKEND, APP_PATH, APP_NAME, CONF_PATH, API_PATH,
    INDEX_HTML, LOGIN_HTML, LOGINRESULT_HTML,
    
    MAIN_HTML: APP_PATH+"/home.html",
    ARTICLE_HTML: APP_PATH+"/article.html",
    LANDING_HTML: APP_PATH+"/landing.html",
    BLOGS_HTML: APP_PATH+"/blogs.html",
    ALL_BLOGS_HTML: APP_PATH+"/allblogs.html",
    MAINBLOG_HTML:APP_PATH+"/mainblog.html",
    BLOGLIST_HTML:APP_PATH+"/bloglist.html",
    BLOGARTICLE_HTML:APP_PATH+"/blogarticle.html",
    BLOGARTICLE_NEW_HTML:APP_PATH+"/blogarticle_n.html",
    INDEX_HTML: APP_PATH+"/index.html",
    CONTACTUS_HTML: APP_PATH+"/contactus.html",
    PRODUCTINQUIRIES_HTML:APP_PATH+"/productinquiries.html",
    RESOURCE_HTML: APP_PATH+"/resource.html",
    LICENSE_HTML: APP_PATH+"/license.html",
    UPDATEBLOG_HTML: APP_PATH+"/updateblog.html",
    COMPONENT_BLOG_LIST: APP_PATH+"/components/blog-list/blog-list.html",
    COMPONENT_BLOG_CARDS: APP_PATH+"/components/blog-cards/blog-cards.html",
    ERROR_HTML: FRONTEND+"/framework/error.html",
    CMS_ROOT_URL: `${APP_PATH}/articles`,
    HOSTNAME: APP_PATH+"/conf/hostname.json",

    // CMS APIs
    API_CMS_DIR_CONTENTS: API_PATH+"/cmsdirlisting",
    API_NAV_MENU_LISTING: API_PATH+"/navmenulisting",
    API_SEND_CONTACTS_EMAIL: API_PATH+"/sendcontactsemail",
    API_SEND_PRODUCT_INQUIRIES: API_PATH+"/sendproductinquiries",
    API_GET_BLOG_LIST: API_PATH+"/getBlogList",
    API_UPDATE_BLOG: API_PATH+"/updateBlog",
    API_ADD_BLOG: API_PATH+"/addBlog",
    API_CHECK_FOLDER: API_PATH+"/checkFolder",
    API_GET_IMAGE: API_PATH+"/getBlogImage",
    API_DELETE_BLOG: API_PATH+"/deleteBlog",

    SESSION_NOTE_ID: "com_monkshu_app_mnkp",

    // Login constants
    MIN_PASS_LENGTH: 8,
    API_LOGIN: `${API_PATH}/login`,
    BCRYPT_SALT: "$2a$10$VFyiln/PpFyZc.ABoi4ppf",
    TIMEOUT: 3600000,
    USERID: "id",
    USERNAME: "username",
    USERORG: "userorg",
    USER_ROLE: "user",
    GUEST_ROLE: "guest",
    ADMIN_ROLE: "admin",
    TKMLOGIN_LIB: `${APP_PATH}/3p/tkmlogin.mjs`,
    
    API_KEYS: {"*":"fheiwu98237hjief8923ydewjidw834284hwqdnejwr79389"},
    KEY_HEADER: "X-API-Key"
}

APP_CONSTANTS.PERMISSIONS_MAP = {
    admin:[APP_CONSTANTS.INDEX_HTML,APP_CONSTANTS.MAIN_HTML,APP_CONSTANTS.ARTICLE_HTML,APP_CONSTANTS.LANDING_HTML,APP_CONSTANTS.BLOGS_HTML,APP_CONSTANTS.BLOGARTICLE_HTML,APP_CONSTANTS.BLOGARTICLE_NEW_HTML,APP_CONSTANTS.MAINBLOG_HTML,APP_CONSTANTS.BLOGLIST_HTML,APP_CONSTANTS.CONTACTUS_HTML,APP_CONSTANTS.PRODUCTINQUIRIES_HTML,APP_CONSTANTS.RESOURCE_HTML,APP_CONSTANTS.LICENSE_HTML,APP_CONSTANTS.UPDATEBLOG_HTML, APP_CONSTANTS.LOGIN_HTML, APP_CONSTANTS.LOGINRESULT_HTML, APP_CONSTANTS.ALL_BLOGS_HTML, APP_CONSTANTS.ERROR_HTML],
    user:[APP_CONSTANTS.INDEX_HTML,APP_CONSTANTS.MAIN_HTML,APP_CONSTANTS.ARTICLE_HTML,APP_CONSTANTS.LANDING_HTML,APP_CONSTANTS.BLOGS_HTML,APP_CONSTANTS.BLOGARTICLE_HTML,APP_CONSTANTS.BLOGARTICLE_NEW_HTML,APP_CONSTANTS.MAINBLOG_HTML,APP_CONSTANTS.BLOGLIST_HTML,APP_CONSTANTS.CONTACTUS_HTML,APP_CONSTANTS.PRODUCTINQUIRIES_HTML,APP_CONSTANTS.RESOURCE_HTML,APP_CONSTANTS.LICENSE_HTML,APP_CONSTANTS.UPDATEBLOG_HTML, APP_CONSTANTS.LOGIN_HTML, APP_CONSTANTS.LOGINRESULT_HTML, APP_CONSTANTS.ALL_BLOGS_HTML, APP_CONSTANTS.ERROR_HTML],
    guest:[APP_CONSTANTS.INDEX_HTML,APP_CONSTANTS.MAIN_HTML,APP_CONSTANTS.ARTICLE_HTML,APP_CONSTANTS.LANDING_HTML,APP_CONSTANTS.BLOGS_HTML,APP_CONSTANTS.BLOGARTICLE_HTML,APP_CONSTANTS.BLOGARTICLE_NEW_HTML,APP_CONSTANTS.MAINBLOG_HTML,APP_CONSTANTS.BLOGLIST_HTML,APP_CONSTANTS.CONTACTUS_HTML,APP_CONSTANTS.PRODUCTINQUIRIES_HTML,APP_CONSTANTS.RESOURCE_HTML,APP_CONSTANTS.LICENSE_HTML,APP_CONSTANTS.UPDATEBLOG_HTML,APP_CONSTANTS.LOGIN_HTML, APP_CONSTANTS.LOGINRESULT_HTML, APP_CONSTANTS.ALL_BLOGS_HTML, APP_CONSTANTS.ERROR_HTML]
}